Add Orchard generators
zcash-hackworks/zcash-test-vectors pull request #18
Opened 2021-04-22 05:30 UTC by therealyingtong

This is based on #17 which has not yet been merged.

2021-04-27 04:27 UTC, str4d requested changes

2021-04-27 04:27 UTC, str4d commented on orchard_generators.py
> +# Used in SinsemillaCommit (https://zips.z.cash/protocol/nu5.pdf#sinsemillacommitments)
```suggestion
# Used in SinsemillaCommit (https://zips.z.cash/protocol/nu5.pdf#concretesinsemillacommit)
```

2021-04-27 04:27 UTC, str4d commented on orchard_generators.py
> +NOTE_COMMITMENT_Q = group_hash(b'z.cash:Orchard-NoteCommit-M', b'')
The domain separator for SinsemillaHashToPoint is used as the message for GroupHash when deriving Q:
```suggestion
NOTE_COMMITMENT_Q = group_hash(b'z.cash:SinsemillaQ', b'z.cash:Orchard-NoteCommit-M')
```

2021-04-27 04:27 UTC, str4d commented on orchard_generators.py
> +# Used in SinsemillaShortCommit (https://zips.z.cash/protocol/nu5.pdf#sinsemillacommitments)
```suggestion
# Used in SinsemillaShortCommit (https://zips.z.cash/protocol/nu5.pdf#concretesinsemillacommit)
```

2021-04-27 04:27 UTC, str4d commented on orchard_generators.py
> +IVK_COMMITMENT_Q = group_hash(b'z.cash:Orchard-CommitIvk-M', b'')
```suggestion
IVK_COMMITMENT_Q = group_hash(b'z.cash:SinsemillaQ', b'z.cash:Orchard-CommitIvk-M')
```

2021-04-27 04:27 UTC, str4d commented on orchard_generators.py
> +MERKLE_CRH_Q = group_hash(b'z.cash:Orchard-MerkleCRH', b'')
```suggestion
MERKLE_CRH_Q = group_hash(b'z.cash:SinsemillaQ', b'z.cash:Orchard-MerkleCRH')
```

2021-05-06 15:04 UTC, daira commented
This is included in #28.

2021-05-06 15:18 UTC, daira commented
Closing in favour of #21 (to be merged first) and then #28.

2021-05-06 15:18 UTC, closed without merging