Poseidon implementation
zcash-hackworks/zcash-test-vectors pull request #27
Opened 2021-04-30 11:11 UTC by therealyingtong

Uses test vectors from https://github.com/daira/pasta-hadeshash/commit/cdab5252d0ec675780e9f8c3d09fdb7a0a71d3ff.

2021-04-30 11:36 UTC, daira approved these changes
ACK. Feel free to add more test vectors!

2021-05-07 02:51 UTC, str4d commented on orchard_poseidon.py
> +    return perm([x, y, CAPACITY_ELEMENT])
Move these into `orchard_poseidon_hash.py` and then add test vector generation (e.g. some sequential inputs and some random) both here for `perm` and in `orchard_poseidon_hash.py` for `poseidon_hash`.

2021-05-07 04:46 UTC, str4d requested changes

2021-05-07 04:46 UTC, str4d commented on orchard_poseidon_hash.py
> +        'poseidon_hash',
This is used in a comment; it should be the filename.
```suggestion
        'orchard_poseidon_hash',
```

2021-05-07 04:46 UTC, str4d commented on orchard_poseidon_hash.py
> +    return perm([x, y, CAPACITY_ELEMENT])
The hash function only returns the first element of the state:
```suggestion
    return perm([x, y, CAPACITY_ELEMENT])[0]
```

2021-05-07 04:46 UTC, str4d commented on orchard_poseidon_hash.py
> +            ('output', '[[u8; 32]; 3]'),
```suggestion
            ('output', '[u8; 32]'),
```

2021-05-07 04:46 UTC, str4d commented on orchard_poseidon_hash.py
> +            'output': list(map(bytes, poseidon_hash(input[0], input[1]))),
```suggestion
            'output': bytes(poseidon_hash(input[0], input[1])),
```

2021-05-07 04:46 UTC, str4d commented on orchard_poseidon.py
> +        'poseidon_perm',
```suggestion
        'orchard_poseidon',
```

2021-05-07 04:46 UTC, str4d commented on orchard_poseidon.py
> +    state_words = list(input_words)
```suggestion
    state_words = list(input_words)
    assert len(state_words) == t
```

2021-05-08 02:18 UTC, str4d approved these changes
ACK after comments are addressed.

2021-05-08 02:18 UTC, str4d commented on orchard_poseidon.py
> +import numpy as np
Document this dependency in `README.md`.

2021-05-08 02:18 UTC, str4d commented on orchard_poseidon.py
> +]
```suggestion
]
assert len(ROUND_CONSTANTS) == (R_F + R_P) * t
```

2021-05-08 02:18 UTC, str4d commented on orchard_poseidon.py
> +ROUND_CONSTANTS = [
I checked this.

2021-05-08 02:18 UTC, str4d commented on orchard_poseidon.py
> +MDS_MATRIX = [
I checked this.

2021-05-08 02:18 UTC, str4d commented on orchard_poseidon.py
> +            'output': list(map(bytes, perm(input))),
```suggestion
            ('initial_state', '[[u8; 32]; 3]'),
            ('final_state', '[[u8; 32]; 3]'),
        ),
        [{
            'initial_state': list(map(bytes, input)),
            'final_state': list(map(bytes, perm(input))),
```

2021-05-08 18:54 UTC, merged

2021-05-09 05:50 UTC, daira reviewed
Post-hoc utACK.